"""empty message

Revision ID: 479d2a2bc2e9
Revises: 55d06c6b313c
Create Date: 2015-12-02 10:14:00.528445

"""

# revision identifiers, used by Alembic.
revision = '479d2a2bc2e9'
down_revision = '55d06c6b313c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=80), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=False),
    sa.Column('address2', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address1'),
    sa.UniqueConstraint('address2'),
    sa.UniqueConstraint('warehouse_name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=80), nullable=False),
    sa.Column('item_name', sa.String(length=80), nullable=False),
    sa.Column('item_group_id', sa.Integer(), nullable=True),
    sa.Column('default_unit_id', sa.Integer(), nullable=True),
    sa.Column('default_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['default_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['item_group_id'], ['item_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('item_code')
    )
    op.drop_table('companys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items')
    op.drop_table('warehouses')
    op.drop_table('companies')
    ### end Alembic commands ###
