"""empty message

Revision ID: 47cb7a9d51bb
Revises: 25f7b5728d08
Create Date: 2015-11-13 17:18:31.016147

"""

# revision identifiers, used by Alembic.
revision = '47cb7a9d51bb'
down_revision = '25f7b5728d08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=80), nullable=False),
    sa.Column('must_be_whole_number', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name')
    )
    op.create_table('item_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_group_name', sa.String(length=80), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_group_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_groups')
    op.drop_table('units')
    op.drop_table('companys')
    ### end Alembic commands ###
