"""empty message

Revision ID: 55d06c6b313c
Revises: None
Create Date: 2015-11-25 17:06:53.294254

"""

# revision identifiers, used by Alembic.
revision = '55d06c6b313c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_group_name', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['item_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_group_name')
    )
    op.create_table('companys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=80), nullable=False),
    sa.Column('must_be_whole_number', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('companys')
    op.drop_table('item_groups')
    ### end Alembic commands ###
